name: SPP Commit Check

on:
  pull_request:
    branches:
      - main

jobs:
  verify_commits:
    runs-on: ubuntu-latest

    steps:
    - name: Get pull request details
      id: pr_details
      run: echo "::set-output name=pull_request_number::${{ github.event.pull_request.number }}"
      
    - name: Get repo name
      id: repo_name
      run: echo "::set-output name=repo_name::${{ github.repository }}"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get SPP Commits
      id: spp_commits
      run: |
        commits=$(git log --pretty=format:"%s" HEAD...${{ github.base_ref }} | grep "^SPP-[0-9]\{5\}" | awk '{print $1}')
        echo "::set-output name=spp_commits::$commits"

    - name: Add SPP Commit List as Comment
      if: steps.spp_commits.outputs.spp_commits != ''
      uses: peter-evans/create-or-update-pull-request-comment@v1
      with:
        pull_request_number: ${{ steps.pr_details.outputs.pull_request_number }}
        repository_name: ${{ steps.pr_details.outputs.repo_name }}
        comment: |
          ## SPP Commits
          $(echo "${{ steps.spp_commits.outputs.spp_commits }}" | tr '\n' '\n' | sort | uniq)
