name: Verify SPP Commit Messages

on:
  pull_request:
    branches:
      - main

jobs:
  verify_commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Commit Messages
      run: |
        git log origin/${{ github.head_ref }}..HEAD --pretty=format:"%s" > commits.txt

    - name: Filter and Format SPP Commits
      run: |
        cat commits.txt | grep "^SPP-[0-9]\{5\}" | sed "s/SPP-[0-9]\{5\}//g" | sed "s/^[ \t]*//" | sort -u > filtered_commits.txt

    - name: Add Comment to Pull Request
      uses: elgohr/Add-Comment-Action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: |
          List of Unique SPP Commit Messages:
          $(cat filtered_commits.txt | awk '{print " - "$0}')
