name: Add SPP- commits as comment on pull request

on:
  pull_request:
    types: [opened]

jobs:
  process_commits:
    runs-on: ubuntu-latest

    steps:
    - name: Check branch name
      if: contains(github.event.pull_request.head.ref, 'main')
      run: |
        echo "Branch name contains 'main', continuing with action."

    - name: Get all commits
      run: |
        commits=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits)
        echo "Commits: ${commits}"

    - name: Filter SPP- commits
      run: |
        filtered_commits=$(echo "$commits" | jq '.[] | select(.message | startswith("SPP-")) | select(.message | test("SPP-[0-9][0-9][0-9][0-9][0-9]"))')
        echo "Filtered commits: ${filtered_commits}"

    - name: Cut commit message
      run: |
        cut_commits=$(echo "$filtered_commits" | jq '.[].message | capture("(SPP-[0-9][0-9][0-9][0-9][0-9]).*")')
        echo "Cut commits: ${cut_commits}"

    - name: Add unique list as comment on pull request
      run: |
        unique_commits=$(echo "$cut_commits" | sort | uniq)
        comment="## SPP- Commits\n\n$(echo "$unique_commits" | awk '{print "-"$0}')"
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -X POST -d "{\"body\":\"$comment\"}" \
        https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
