name: Check for SPP- Commits

on:
  pull_request:
    branches:
      - main

jobs:
  verify_commits:
    runs-on: ubuntu-latest

    steps:
    - name: Get pull request commits
      id: get_commits
      run: |
        echo "::set-output name=commits::$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${GITHUB_PULL_REQUEST}/commits | jq '.[].sha')"

    - name: Filter SPP- Commits
      id: filter_commits
      run: |
        echo "::set-output name=filtered_commits::$(echo "${GITHUB_EVENT_PATH}" | jq '."pull_request".commits | map(select(.message | test("^SPP-[0-9]{5}.*")) | .message) | unique | join(",\n")')"

    - name: Cut commit message
      id: cut_commit_message
      run: |
        echo "::set-output name=cut_commits::$(echo "${steps.filter_commits.outputs.filtered_commits}" | sed 's/^SPP-[0-9]\{5\} //g')"

    - name: Add comment to pull request
      if: steps.cut_commit_message.outputs.cut_commits != ''
      run: |
        curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -X POST \
        -d "{\"body\":\"Commits related to SPP-: \n\`\`\`\n${{ steps.cut_commit_message.outputs.cut_commits }}\n\`\`\`\"}" \
        https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$GITHUB_PULL_REQUEST/comments
        
